### PR TITLE
Load .env before starting newrelic-admin

### LINKED ISSUE #81: New relic and dotenv
Using the latest version of the template and margarita, I've had trouble getting the newrelic python agent functioning properly. After some debugging today, I believe the new relic environment variables are loaded too late for ``newrelic-admin`` to see them. Specifically, even though the [wsgi file](https://github.com/caktus/django-project-template/blob/master/project_name/wsgi.py#L14-L16) loads the environment variables:

```python
from . import load_env
load_env.load_env()
```

My hunch is that the ``load_env()`` command isn't executed in time for the ``newrelic-admin run-program`` wrapper script to catch the enivonment variables [here](https://github.com/caktus/margarita/blob/develop/project/web/gunicorn.conf#L2):

```ini
command={% if use_newrelic %}{{ virtualenv_root }}/bin/newrelic-admin run-program {% endif %}{{ virtualenv_root }}/bin/gunicorn {{ pillar['project_name'] }}.wsgi:application --bind=0.0.0.0:8000 --workers={{ grains['num_cpus'] * 2 + 1 }}
```

To test, if I export ``NEW_RELIC_LICENSE_KEY``, ``NEW_RELIC_LOG``, and ``NEW_RELIC_APP_NAME`` and then run the above supervisor command manually, New Relic starts reporting as expected.

Has anyone else run into this issue?

### PR DESCRIPTION
**Pull request by dpoirier**
Fixes #81

### CODE REVIEW

**Comment by mlavin** [comment]
If we are doing this then do we need the `load_env()` calls in the `wsgi.py` and `celery.py` files in the project template? I don't think that we do since the environment will already be populated.

**Comment by dpoirier** [comment]
If we only ever started Django from these supervisor configurations, we wouldn't need the `load_env()` calls in `wsgi.py` and `celery.py`.  But it seems harmless to keep them, and means we can run them some other way and be sure the env is still set.

**Comment by dpoirier** [comment]
Any other comments on this?

**Comment by vkurup** [comment]
I say :shipit:. I feel like we haven't gained much with the dotenv switch. Well, we're not manually delineating each env var in each supervisor config file... we only need to remember to wrap each command we might ever write with dotenv.sh, so that's an improvement.

**Comment by mlavin** [comment]
Agreed :shipit:

**Pull request merged**
