### PR TITLE
Allow configuring requirements file

### PR DESCRIPTION
**Pull request by rebecca-caktus**

### CODE REVIEW

**Comment by dpoirier** [comment]
Looks reasonable. Would like to see an update to the developer docs for margarita?

**Comment by rebecca-caktus** [comment]
@dpoirier Perhaps I can add a note [here](https://github.com/caktus/developer-documentation/blob/19523fe8a5a66fec382b28ff4085efe17cb21c77/source/deploy/system-deploy-interface.rst#python-dependencies). Is there any where else you'd like to see updated?

**Comment by dpoirier** [comment]
It needs to be documented here: http://caktus.github.io/developer-documentation/margarita/states.html#project-venv since that's the state that's going to be affected.

**Comment by rebecca-caktus** [comment]
@dpoirier Updated.

**Comment by dpoirier** [comment]
:+1:

**Pull request merged**
