### PR TITLE
Move default states from the project template into margarita

### PR DESCRIPTION
**Pull request by dpoirier**
Existing projects will still have their own copies of these states, which will take precedence over these.

Once a corresponding change is made in the django-project-template to remove these states, new projects will not have their own copies of these, and will use them from margarita, so they can benefit from future bug fixes in margarita.

### CODE REVIEW

**Comment by mlavin** [comment]
There is a potentially related issue to remove states which are now included under the `project` tree. See #47 I don't know whether it needs to be combined here or not but it would be good to get them in the same release.

**Comment by mlavin** [comment]
Remaining questions to answer:

- Document expected available pillar variables
- Document the extension of these states in a project

**Comment by dpoirier** [comment]
I've removed some of the duplicate states that were mentioned.  I'm not seeing where the py27/py33 duplicates are though.

**Comment by mlavin** [comment]
The `python-pkgs` in `project.venv` duplicates the logic in `python/27.sls` and `python/33.sls` in a more general fashion.

**Comment by dpoirier** [comment]
Cleaned up python logic and added docs for pillar variables.

**Comment by dpoirier** [comment]
This and the corresponding pull  https://github.com/caktus/django-project-template/issues/195 have been updated and are ready for review again.

**Comment by mlavin** [comment]
:rocket:

**Pull request merged**
