### PR TITLE
Support dotenv in deploy

### LINKED ISSUE #65: Consider a .env file for configuring env vars for server processes
See: caktus/django-project-template#166

Have gunicorn, celery, celerybeat load environment variables from a common `.env` file.

### PR DESCRIPTION
**Pull request by vkurup**
Closes #65 

A couple issues that I still need to address:
- [x] Docs for adding `dotenv` command to `celery.py` so that celery workers can access the environment
- [x] Figure out how to coordinate this with the corresponding project-template PR

### CODE REVIEW

**Comment by dpoirier** [comment]
The README in django-project-template seems to be where docs for setting up your project are ending up, so that seems like the place for the docs on enabling Celery.

**Comment by mlavin** [comment]
What's left to move this forward?

**Comment by vkurup** [comment]
I fixed the merge conflict and added the new 'DOMAIN' env var to dotenv. If this looks good, I'll merge and release, so that I can merge caktus/django-project-template#200

**Comment by dpoirier** [comment]
:+1:

**Pull request merged**
